# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/test_edc.xdc

# IP: ip/state_test3/state_test3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==state_test3 || ORIG_REF_NAME==state_test3} -quiet] -quiet

# IP: ip/C19_1/C19.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==C19 || ORIG_REF_NAME==C19} -quiet] -quiet
