# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7k160tffg676-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/logos/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/logos/project_1/project_1.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/logos/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/logos/Desktop/2333.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/logos/Desktop/Crazymhr.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/Users/logos/Desktop/Crazymhr.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/16.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/33.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/41.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/3.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/25.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/15.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/4.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/32.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/42.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/50.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/24.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/35.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/52.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/22.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/19.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/6.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/49.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/36.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/18.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/10.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/23.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/51.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/40.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/21.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/34.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/17.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/47.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/48.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/5.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/46.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/29.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/12.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/38.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/28.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/45.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/7.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/20.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/37.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/11.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/1.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/27.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/30.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/44.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/14.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/2.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/9.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/13.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/31.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/43.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/39.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/26.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/8.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/state1.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/lwcsb1.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/lwcsb2.coe
add_files C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/reference.coe
add_files C:/PUKECCC/reference.coe
add_files C:/PUKECCC/2.coe
add_files C:/PUKECCC/3.coe
add_files C:/PUKECCC/5.coe
add_files C:/PUKECCC/6.coe
add_files C:/PUKECCC/7.coe
add_files C:/PUKECCC/8.coe
add_files C:/PUKECCC/9.coe
add_files C:/PUKECCC/10.coe
add_files C:/PUKECCC/11.coe
add_files C:/PUKECCC/12.coe
add_files C:/PUKECCC/13.coe
add_files C:/PUKECCC/14.coe
add_files C:/PUKECCC/15.coe
add_files C:/PUKECCC/16.coe
add_files C:/PUKECCC/17.coe
add_files C:/PUKECCC/18.coe
add_files C:/PUKECCC/19.coe
add_files C:/PUKECCC/20.coe
add_files C:/PUKECCC/21.coe
add_files C:/PUKECCC/22.coe
add_files C:/PUKECCC/23.coe
add_files C:/PUKECCC/24.coe
add_files C:/PUKECCC/25.coe
add_files C:/PUKECCC/26.coe
add_files C:/PUKECCC/27.coe
add_files C:/PUKECCC/28.coe
add_files C:/PUKECCC/29.coe
add_files C:/PUKECCC/30.coe
add_files C:/PUKECCC/31.coe
add_files C:/PUKECCC/32.coe
add_files C:/PUKECCC/33.coe
add_files C:/PUKECCC/34.coe
add_files C:/PUKECCC/36.coe
add_files C:/PUKECCC/37.coe
add_files C:/PUKECCC/38.coe
add_files C:/PUKECCC/39.coe
add_files C:/PUKECCC/40.coe
add_files C:/PUKECCC/41.coe
add_files C:/PUKECCC/42.coe
add_files C:/PUKECCC/43.coe
add_files C:/PUKECCC/44.coe
add_files C:/PUKECCC/45.coe
add_files C:/PUKECCC/46.coe
add_files C:/PUKECCC/47.coe
add_files C:/PUKECCC/48.coe
add_files C:/PUKECCC/49.coe
add_files C:/PUKECCC/50.coe
add_files C:/PUKECCC/51.coe
add_files C:/PUKECCC/52.coe
add_files C:/PUKECCC/35.coe
add_files C:/PUKECCC/4.coe
add_files C:/PUKECCC/state1.coe
add_files C:/PUKECCC/lwcsb1.coe
add_files C:/PUKECCC/lwcsb2.coe
add_files C:/PUKECCC/function2.coe
add_files C:/PUKECCC/function1.coe
add_files C:/PUKECCC/function0.coe
add_files C:/PUKECCC/state2.coe
add_files C:/PUKECCC/state3.coe
add_files C:/PUKECCC/state4.coe
add_files C:/PUKECCC/max_test12.coe
add_files C:/PUKECCC/start12.coe
add_files C:/PUKECCC/fail12.coe
add_files C:/PUKECCC/victory12.coe
add_files C:/PUKECCC/state5.coe
add_files C:/PUKECCC/smallFail12.coe
add_files C:/PUKECCC/smallVictory12.coe
read_verilog -library xil_defaultlib {
  C:/Users/logos/project_1/project_1.srcs/sources_1/imports/logos/OneDrive/FPGA/RSC-7-60-38-6-3-5-80/bigProgram2018/VGAdemo/Seg7Decode.v
  C:/Users/logos/project_1/project_1.srcs/sources_1/imports/logos/OneDrive/FPGA/RSC-7-60-38-6-3-5-80/bigProgram2018/VGAdemo/Seg7Remap.v
  C:/Users/logos/project_1/project_1.srcs/sources_1/imports/logos/OneDrive/FPGA/RSC-7-60-38-6-3-5-80/bigProgram2018/VGAdemo/SegmentDecoder.v
  C:/Users/logos/project_1/project_1.srcs/sources_1/imports/logos/OneDrive/FPGA/RSC-7-60-38-6-3-5-80/bigProgram2018/VGAdemo/vgac.v
  C:/Users/logos/project_1/project_1.srcs/sources_1/imports/logos/OneDrive/FPGA/RSC-7-60-38-6-3-5-80/bigProgram2018/VGAdemo/Top.v
  C:/Users/logos/project_1/project_1.srcs/sources_1/new/ip_control.v
  C:/Users/logos/project_1/project_1.srcs/sources_1/new/active.v
  C:/Users/logos/project_1/project_1.srcs/sources_1/new/nextSelect.v
  C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/FindPixel.v
  C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/Display.v
  C:/Users/logos/project_1/project_1.srcs/sources_1/imports/MyMarquee/DispNum.vf
  C:/Users/logos/project_1/project_1.srcs/sources_1/imports/MyMarquee/clkdiv.v
  C:/Users/logos/project_1/project_1.srcs/sources_1/imports/top4/pbdebounce.v
  C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/Keyboard.v
  C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/Debounce.v
  C:/Users/logos/project_1/project_1.srcs/sources_1/new/keyActive.v
  C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/Eliminate.v
  C:/Users/logos/project_1/project_1.srcs/sources_1/imports/PUKECCC/Bottom.v
  C:/Users/logos/project_1/project_1.srcs/sources_1/imports/VGAdemo/Seg7Device.v
  C:/Users/logos/project_1/project_1.srcs/sources_1/imports/VGAdemo/ShiftReg.v
}
read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/state_test3/state_test3.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/state_test3/state_test3_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C19_1/C19.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C19_1/C19_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/PICTURE/PICTURE.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/PICTURE/PICTURE_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C1/C1.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C1/C1_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C2/C2.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C2/C2_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C3_1/C3.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C3_1/C3_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C5/C5.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C5/C5_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C6_1/C6.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C6_1/C6_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C7/C7.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C7/C7_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C8/C8.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C8/C8_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C9/C9.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C9/C9_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C10/C10.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C10/C10_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C11/C11.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C11/C11_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C12/C12.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C12/C12_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C13/C13.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C13/C13_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C14/C14.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C14/C14_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C15_1/C15.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C15_1/C15_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C16_1/C16.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C16_1/C16_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C17/C17.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C17/C17_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C18/C18.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C18/C18_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C20/C20.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C20/C20_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C21/C21.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C21/C21_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C22_1/C22.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C22_1/C22_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C23/C23.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C23/C23_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C24_1/C24.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C24_1/C24_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C25_1/C25.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C25_1/C25_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C26/C26.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C26/C26_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C27/C27.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C27/C27_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C28/C28.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C28/C28_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C29/C29.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C29/C29_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C30/C30.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C30/C30_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C31/C31.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C31/C31_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C32_1/C32.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C32_1/C32_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C33_1/C33.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C33_1/C33_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C34/C34.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C34/C34_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C36/C36.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C36/C36_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C37/C37.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C37/C37_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C38/C38.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C38/C38_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C39_1/C39.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C39_1/C39_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C40/C40.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C40/C40_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C41_1/C41.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C41_1/C41_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C42_1/C42.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C42_1/C42_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C43/C43.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C43/C43_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C44/C44.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C44/C44_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C45/C45.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C45/C45_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C46/C46.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C46/C46_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C47/C47.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C47/C47_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C48/C48.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C48/C48_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C49_1/C49.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C49_1/C49_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C50_1/C50.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C50_1/C50_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C51/C51.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C51/C51_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C52_1/C52.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C52_1/C52_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C35_1/C35.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C35_1/C35_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C4_1/C4.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C4_1/C4_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/first/first.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/first/first_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/second/second.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/second/second_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/Reference_5/Reference.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/Reference_5/Reference_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/function2/function2.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/function2/function2_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/function1/function1.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/function1/function1_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/function0/function0.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/function0/function0_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/state_test_1/state_test.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/state_test_1/state_test_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/state_test2/state_test2.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/state_test2/state_test2_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/state_test4/state_test4.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/state_test4/state_test4_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/startP/startP.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/startP/startP_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/failP/failP.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/failP/failP_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/victoryP/victoryP.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/victoryP/victoryP_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/state_test5/state_test5.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/state_test5/state_test5_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/smallFail/smallFail.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/smallFail/smallFail_ooc.xdc]

read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/smallVictory/smallVictory.xci
set_property used_in_implementation false [get_files -all c:/Users/logos/project_1/project_1.srcs/sources_1/ip/smallVictory/smallVictory_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/logos/project_1/project_1.srcs/constrs_1/new/test_edc.xdc
set_property used_in_implementation false [get_files C:/Users/logos/project_1/project_1.srcs/constrs_1/new/test_edc.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Top -part xc7k160tffg676-2L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_utilization_synth.rpt -pb Top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
