# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/logos/project_1/project_1.srcs/sources_1/ip/startP/startP.xci
# IP: The module: 'startP' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/logos/project_1/project_1.srcs/sources_1/ip/startP/startP_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'startP'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/logos/project_1/project_1.srcs/sources_1/ip/startP/startP.xci
# IP: The module: 'startP' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/logos/project_1/project_1.srcs/sources_1/ip/startP/startP_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'startP'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
