# 
# Report generation script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
proc start_step { step } {
  set stopFile ".stop.rst"
  if {[file isfile .stop.rst]} {
    puts ""
    puts "*** Halting run - EA reset detected ***"
    puts ""
    puts ""
    return -code error
  }
  set beginFile ".$step.begin.rst"
  set platform "$::tcl_platform(platform)"
  set user "$::tcl_platform(user)"
  set pid [pid]
  set host ""
  if { [string equal $platform unix] } {
    if { [info exist ::env(HOSTNAME)] } {
      set host $::env(HOSTNAME)
    }
  } else {
    if { [info exist ::env(COMPUTERNAME)] } {
      set host $::env(COMPUTERNAME)
    }
  }
  set ch [open $beginFile w]
  puts $ch "<?xml version=\"1.0\"?>"
  puts $ch "<ProcessHandle Version=\"1\" Minor=\"0\">"
  puts $ch "    <Process Command=\".planAhead.\" Owner=\"$user\" Host=\"$host\" Pid=\"$pid\">"
  puts $ch "    </Process>"
  puts $ch "</ProcessHandle>"
  close $ch
}

proc end_step { step } {
  set endFile ".$step.end.rst"
  set ch [open $endFile w]
  close $ch
}

proc step_failed { step } {
  set endFile ".$step.error.rst"
  set ch [open $endFile w]
  close $ch
}


start_step init_design
set ACTIVE_STEP init_design
set rc [catch {
  create_msg_db init_design.pb
  set_param xicom.use_bs_reader 1
  create_project -in_memory -part xc7k160tffg676-2L
  set_property design_mode GateLvl [current_fileset]
  set_param project.singleFileAddWarning.threshold 0
  set_property webtalk.parent_dir C:/Users/logos/project_1/project_1.cache/wt [current_project]
  set_property parent.project_path C:/Users/logos/project_1/project_1.xpr [current_project]
  set_property ip_output_repo C:/Users/logos/project_1/project_1.cache/ip [current_project]
  set_property ip_cache_permissions {read write} [current_project]
  set_property XPM_LIBRARIES XPM_MEMORY [current_project]
  add_files -quiet C:/Users/logos/project_1/project_1.runs/synth_1/Top.dcp
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/state_test3/state_test3.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C19_1/C19.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/PICTURE/PICTURE.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C1/C1.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C2/C2.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C3_1/C3.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C5/C5.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C6_1/C6.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C7/C7.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C8/C8.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C9/C9.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C10/C10.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C11/C11.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C12/C12.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C13/C13.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C14/C14.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C15_1/C15.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C16_1/C16.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C17/C17.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C18/C18.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C20/C20.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C21/C21.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C22_1/C22.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C23/C23.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C24_1/C24.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C25_1/C25.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C26/C26.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C27/C27.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C28/C28.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C29/C29.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C30/C30.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C31/C31.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C32_1/C32.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C33_1/C33.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C34/C34.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C36/C36.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C37/C37.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C38/C38.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C39_1/C39.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C40/C40.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C41_1/C41.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C42_1/C42.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C43/C43.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C44/C44.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C45/C45.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C46/C46.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C47/C47.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C48/C48.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C49_1/C49.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C50_1/C50.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C51/C51.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C52_1/C52.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C35_1/C35.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C4_1/C4.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/first/first.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/second/second.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/Reference_5/Reference.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/function2/function2.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/function1/function1.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/function0/function0.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/state_test_1/state_test.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/state_test2/state_test2.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/state_test4/state_test4.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/startP/startP.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/failP/failP.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/victoryP/victoryP.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/state_test5/state_test5.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/smallFail/smallFail.xci
  read_ip -quiet C:/Users/logos/project_1/project_1.srcs/sources_1/ip/smallVictory/smallVictory.xci
  read_xdc C:/Users/logos/project_1/project_1.srcs/constrs_1/new/test_edc.xdc
  link_design -top Top -part xc7k160tffg676-2L
  close_msg_db -file init_design.pb
} RESULT]
if {$rc} {
  step_failed init_design
  return -code error $RESULT
} else {
  end_step init_design
  unset ACTIVE_STEP 
}

start_step opt_design
set ACTIVE_STEP opt_design
set rc [catch {
  create_msg_db opt_design.pb
  opt_design 
  write_checkpoint -force Top_opt.dcp
  create_report "impl_1_opt_report_drc_0" "report_drc -file Top_drc_opted.rpt -pb Top_drc_opted.pb -rpx Top_drc_opted.rpx"
  close_msg_db -file opt_design.pb
} RESULT]
if {$rc} {
  step_failed opt_design
  return -code error $RESULT
} else {
  end_step opt_design
  unset ACTIVE_STEP 
}

start_step place_design
set ACTIVE_STEP place_design
set rc [catch {
  create_msg_db place_design.pb
  if { [llength [get_debug_cores -quiet] ] > 0 }  { 
    implement_debug_core 
  } 
  place_design 
  write_checkpoint -force Top_placed.dcp
  create_report "impl_1_place_report_io_0" "report_io -file Top_io_placed.rpt"
  create_report "impl_1_place_report_utilization_0" "report_utilization -file Top_utilization_placed.rpt -pb Top_utilization_placed.pb"
  create_report "impl_1_place_report_control_sets_0" "report_control_sets -verbose -file Top_control_sets_placed.rpt"
  close_msg_db -file place_design.pb
} RESULT]
if {$rc} {
  step_failed place_design
  return -code error $RESULT
} else {
  end_step place_design
  unset ACTIVE_STEP 
}

start_step route_design
set ACTIVE_STEP route_design
set rc [catch {
  create_msg_db route_design.pb
  route_design 
  write_checkpoint -force Top_routed.dcp
  create_report "impl_1_route_report_drc_0" "report_drc -file Top_drc_routed.rpt -pb Top_drc_routed.pb -rpx Top_drc_routed.rpx"
  create_report "impl_1_route_report_methodology_0" "report_methodology -file Top_methodology_drc_routed.rpt -pb Top_methodology_drc_routed.pb -rpx Top_methodology_drc_routed.rpx"
  create_report "impl_1_route_report_power_0" "report_power -file Top_power_routed.rpt -pb Top_power_summary_routed.pb -rpx Top_power_routed.rpx"
  create_report "impl_1_route_report_route_status_0" "report_route_status -file Top_route_status.rpt -pb Top_route_status.pb"
  create_report "impl_1_route_report_timing_summary_0" "report_timing_summary -max_paths 10 -file Top_timing_summary_routed.rpt -pb Top_timing_summary_routed.pb -rpx Top_timing_summary_routed.rpx -warn_on_violation "
  create_report "impl_1_route_report_incremental_reuse_0" "report_incremental_reuse -file Top_incremental_reuse_routed.rpt"
  create_report "impl_1_route_report_clock_utilization_0" "report_clock_utilization -file Top_clock_utilization_routed.rpt"
  create_report "impl_1_route_report_bus_skew_0" "report_bus_skew -warn_on_violation -file Top_bus_skew_routed.rpt -pb Top_bus_skew_routed.pb -rpx Top_bus_skew_routed.rpx"
  close_msg_db -file route_design.pb
} RESULT]
if {$rc} {
  write_checkpoint -force Top_routed_error.dcp
  step_failed route_design
  return -code error $RESULT
} else {
  end_step route_design
  unset ACTIVE_STEP 
}

start_step write_bitstream
set ACTIVE_STEP write_bitstream
set rc [catch {
  create_msg_db write_bitstream.pb
  set_property XPM_LIBRARIES XPM_MEMORY [current_project]
  catch { write_mem_info -force Top.mmi }
  write_bitstream -force Top.bit 
  catch {write_debug_probes -quiet -force Top}
  catch {file copy -force Top.ltx debug_nets.ltx}
  close_msg_db -file write_bitstream.pb
} RESULT]
if {$rc} {
  step_failed write_bitstream
  return -code error $RESULT
} else {
  end_step write_bitstream
  unset ACTIVE_STEP 
}

