# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C33_1/C33.xci
# IP: The module: 'C33' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C33_1/C33_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'C33'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C33_1/C33.xci
# IP: The module: 'C33' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C33_1/C33_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'C33'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
