# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C27/C27.xci
# IP: The module: 'C27' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C27/C27_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'C27'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/logos/project_1/project_1.srcs/sources_1/ip/C27/C27.xci
# IP: The module: 'C27' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/logos/project_1/project_1.srcs/sources_1/ip/C27/C27_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'C27'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
